// <auto-generated />
using System;
using Bruna.Danilo.Testers.Logs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bruna.Danilo.Testers.Api.Migrations.SqliteMigrations
{
    [DbContext(typeof(LogsContext))]
    [Migration("20180728195538_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bruna.Danilo.Testers.Logs.Entities.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LogTypeId");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<string>("MoreInfo");

                    b.Property<int?>("ParentLogId");

                    b.Property<string>("StackTrace");

                    b.Property<int?>("StandardRefId");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("LogTypeId");

                    b.HasIndex("StandardRefId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Bruna.Danilo.Testers.Logs.Entities.LogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("Bruna.Danilo.Testers.Logs.Entities.Logs", b =>
                {
                    b.HasOne("Bruna.Danilo.Testers.Logs.Entities.LogType")
                        .WithMany("Logs")
                        .HasForeignKey("LogTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bruna.Danilo.Testers.Logs.Entities.Logs", "ParentLog")
                        .WithMany()
                        .HasForeignKey("StandardRefId");
                });
#pragma warning restore 612, 618
        }
    }
}
