/*
Script generated by Aqua Data Studio 19.0.0 on Jul-28-2018 12:01:39 PM
Database: Testers
Schema: dbo
Objects: TABLE, INDEX
*/
ALTER TABLE "dbo"."AspNetUserTokens"
	DROP CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
GO
ALTER TABLE "dbo"."AspNetUserRoles"
	DROP CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
GO
ALTER TABLE "dbo"."AspNetUserRoles"
	DROP CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
GO
ALTER TABLE "dbo"."AspNetUserLogins"
	DROP CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
GO
ALTER TABLE "dbo"."AspNetUserClaims"
	DROP CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
GO
ALTER TABLE "dbo"."AspNetRoleClaims"
	DROP CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
GO
DROP INDEX "UserNameIndex" ON "dbo"."AspNetUsers"
GO
DROP INDEX "RoleNameIndex" ON "dbo"."AspNetRoles"
GO
DROP INDEX "IX_AspNetUserRoles_RoleId" ON "dbo"."AspNetUserRoles"
GO
DROP INDEX "IX_AspNetUserLogins_UserId" ON "dbo"."AspNetUserLogins"
GO
DROP INDEX "IX_AspNetUserClaims_UserId" ON "dbo"."AspNetUserClaims"
GO
DROP INDEX "IX_AspNetRoleClaims_RoleId" ON "dbo"."AspNetRoleClaims"
GO
DROP INDEX "EmailIndex" ON "dbo"."AspNetUsers"
GO
DROP TABLE "dbo"."AspNetUsers"
GO
DROP TABLE "dbo"."AspNetUserTokens"
GO
DROP TABLE "dbo"."AspNetUserRoles"
GO
DROP TABLE "dbo"."AspNetUserLogins"
GO
DROP TABLE "dbo"."AspNetUserClaims"
GO
DROP TABLE "dbo"."AspNetRoles"
GO
DROP TABLE "dbo"."AspNetRoleClaims"
GO

CREATE TABLE "dbo"."AspNetRoleClaims"  ( 
	"Id"        	int IDENTITY(1,1) NOT NULL,
	"RoleId"    	nvarchar(450) NOT NULL,
	"ClaimType" 	nvarchar(max) NULL,
	"ClaimValue"	nvarchar(max) NULL,
	CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY CLUSTERED("Id")
)
GO
CREATE TABLE "dbo"."AspNetRoles"  ( 
	"Id"              	nvarchar(450) NOT NULL,
	"Name"            	nvarchar(256) NULL,
	"NormalizedName"  	nvarchar(256) NULL,
	"ConcurrencyStamp"	nvarchar(max) NULL,
	CONSTRAINT "PK_AspNetRoles" PRIMARY KEY CLUSTERED("Id")
)
GO
CREATE TABLE "dbo"."AspNetUserClaims"  ( 
	"Id"        	int IDENTITY(1,1) NOT NULL,
	"UserId"    	nvarchar(450) NOT NULL,
	"ClaimType" 	nvarchar(max) NULL,
	"ClaimValue"	nvarchar(max) NULL,
	CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY CLUSTERED("Id")
)
GO
CREATE TABLE "dbo"."AspNetUserLogins"  ( 
	"LoginProvider"      	nvarchar(450) NOT NULL,
	"ProviderKey"        	nvarchar(450) NOT NULL,
	"ProviderDisplayName"	nvarchar(max) NULL,
	"UserId"             	nvarchar(450) NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY CLUSTERED("LoginProvider","ProviderKey")
)
GO
CREATE TABLE "dbo"."AspNetUserRoles"  ( 
	"UserId"	nvarchar(450) NOT NULL,
	"RoleId"	nvarchar(450) NOT NULL,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY CLUSTERED("UserId","RoleId")
)
GO
CREATE TABLE "dbo"."AspNetUserTokens"  ( 
	"UserId"       	nvarchar(450) NOT NULL,
	"LoginProvider"	nvarchar(450) NOT NULL,
	"Name"         	nvarchar(450) NOT NULL,
	"Value"        	nvarchar(max) NULL,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY CLUSTERED("UserId","LoginProvider","Name")
)
GO
CREATE TABLE "dbo"."AspNetUsers"  ( 
	"Id"                  	nvarchar(450) NOT NULL,
	"UserName"            	nvarchar(256) NULL,
	"NormalizedUserName"  	nvarchar(256) NULL,
	"Email"               	nvarchar(256) NULL,
	"NormalizedEmail"     	nvarchar(256) NULL,
	"EmailConfirmed"      	bit NOT NULL,
	"PasswordHash"        	nvarchar(max) NULL,
	"SecurityStamp"       	nvarchar(max) NULL,
	"ConcurrencyStamp"    	nvarchar(max) NULL,
	"PhoneNumber"         	nvarchar(max) NULL,
	"PhoneNumberConfirmed"	bit NOT NULL,
	"TwoFactorEnabled"    	bit NOT NULL,
	"LockoutEnd"          	datetimeoffset NULL,
	"LockoutEnabled"      	bit NOT NULL,
	"AccessFailedCount"   	int NOT NULL,
	CONSTRAINT "PK_AspNetUsers" PRIMARY KEY CLUSTERED("Id")
)
GO
CREATE NONCLUSTERED INDEX "EmailIndex"
	ON "dbo"."AspNetUsers"("NormalizedEmail")
GO
CREATE NONCLUSTERED INDEX "IX_AspNetRoleClaims_RoleId"
	ON "dbo"."AspNetRoleClaims"("RoleId")
GO
CREATE NONCLUSTERED INDEX "IX_AspNetUserClaims_UserId"
	ON "dbo"."AspNetUserClaims"("UserId")
GO
CREATE NONCLUSTERED INDEX "IX_AspNetUserLogins_UserId"
	ON "dbo"."AspNetUserLogins"("UserId")
GO
CREATE NONCLUSTERED INDEX "IX_AspNetUserRoles_RoleId"
	ON "dbo"."AspNetUserRoles"("RoleId")
GO
CREATE UNIQUE NONCLUSTERED INDEX "RoleNameIndex"
	ON "dbo"."AspNetRoles"("NormalizedName")
	WHERE ([NormalizedName] IS NOT NULL)
GO
CREATE UNIQUE NONCLUSTERED INDEX "UserNameIndex"
	ON "dbo"."AspNetUsers"("NormalizedUserName")
	WHERE ([NormalizedUserName] IS NOT NULL)
GO

ALTER TABLE "dbo"."AspNetRoleClaims"
	ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
	FOREIGN KEY("RoleId")
	REFERENCES "dbo"."AspNetRoles"("Id")
	ON DELETE CASCADE 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "dbo"."AspNetUserClaims"
	ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
	FOREIGN KEY("UserId")
	REFERENCES "dbo"."AspNetUsers"("Id")
	ON DELETE CASCADE 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "dbo"."AspNetUserLogins"
	ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
	FOREIGN KEY("UserId")
	REFERENCES "dbo"."AspNetUsers"("Id")
	ON DELETE CASCADE 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "dbo"."AspNetUserRoles"
	ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
	FOREIGN KEY("UserId")
	REFERENCES "dbo"."AspNetUsers"("Id")
	ON DELETE CASCADE 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "dbo"."AspNetUserRoles"
	ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
	FOREIGN KEY("RoleId")
	REFERENCES "dbo"."AspNetRoles"("Id")
	ON DELETE CASCADE 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "dbo"."AspNetUserTokens"
	ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
	FOREIGN KEY("UserId")
	REFERENCES "dbo"."AspNetUsers"("Id")
	ON DELETE CASCADE 
	ON UPDATE NO ACTION 
GO
